rest.ssl.client:
  bob:
    keyStoreFile: classpath:clientBob.jks
    keyStorePwd: abcdef
    privateKeyPwd: abcdef
  xavier:
    keyStoreFile: classpath:client_xavier.jks
    keyStorePwd: xavier
    privateKeyPwd: xavier
logging:
  level:
    org.apache.http.ssl: DEBUG
